sudo: required
services:
  - docker
# Doku.: https://giorgos.sealabs.net/build-and-test-against-docker-images-in-travis.html
  # https://docs.docker.com/engine/examples/postgresql_service/#testing-the-database
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
  
# Docker cheatsheet: https://github.com/wsargent/docker-cheat-sheet
install:
  - docker build -t chatelao/docker-postgres-osm .
script:
  - docker run -d --name postgres-osm chatelao/docker-postgres-osm
  - docker images
  - docker ps
  - docker run -it --rm --link postgres-osm:pg --entrypoint /bin/bash postgres:9.6.8 -c 'psql -h $PG_PORT_5432_TCP_ADDR -p $PG_PORT_5432_TCP_PORT -U postgres postgres'
