sudo: required
services:
  - docker
# Doku.: https://giorgos.sealabs.net/build-and-test-against-docker-images-in-travis.html
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  - docker build -t chatelao/docker-postgres-osm .
  - docker run chatelao/docker-postgres-osm
script:
  - docker run -it --rm --link some-postgres:postgres chatelao/docker-postgres-osm psql -h postgres -U postgres
